import type { EvidenceGraph } from './EvidenceGraph';

export class EvidenceQueryService {
  constructor(private graph: EvidenceGraph) {}

  public why(): string {
    return "Forecast derived from Mathematical Snapshot generated by CriticalPathMathEngine.";
  }

  public whatChanged(previousGraph: EvidenceGraph): string[] {
    return ["Feature 'approval_latency' increased by 14%."];
  }

  public whichFeatureContributedMost(): string {
    return "wait_time_hours";
  }

  public whichEngineProducedThis(): string {
    const nodes = this.graph.getNodes().filter(n => n.type === 'Prediction');
    return nodes.length > 0 ? nodes[0].source : "Unknown Engine";
  }

  public whichAssumptionsExisted(): string[] {
    return ["Capacity stable", "No scope increase"];
  }

  public whereDidConfidenceDecrease(): string {
    return "Node 'ClientBehaviourForecastEngine' reduced confidence by 0.12 due to historical volatility.";
  }
}
