[pytest]
addopts = -ra -q --html=testing/reports/pytest-html/report.html --junitxml=testing/reports/junit/pytest-results.xml --cov=./testing --cov-report=html:testing/reports/coverage/pytest
testpaths =
    testing/certification
